/**
 * API Service – single entry point for backend communication.
 * Modules: api/config, api/auth, api/turtle, api/sheets.
 */

export {
  AUTH_API_BASE_URL,
  TURTLE_API_BASE_URL,
  getToken,
  setToken,
  removeToken,
} from './api/config';

export {
  apiRequest,
  register,
  login,
  getCurrentUser,
  logout,
  getGoogleAuthUrl,
  getInvitationDetails,
  verifyEmail,
  resendVerificationEmail,
  promoteToAdmin,
  getUsers,
  setUserRole,
  deleteUser,
  isStaffRole,
  isAdminRole,
  isTeamLead,
  isGlobalScope,
  isScopedUser,
  getGroups,
  createGroup,
  updateGroup,
  deleteGroup,
  setGroupAreas,
  setUserMembership,
  getMyGroup,
  claimMember,
  setMemberRank,
  releaseMember,
  ApiError,
} from './api/auth';
export { fetchCommunityGameState, saveCommunityGameState } from './api/communityGame';
export { getBackupWindow, type BackupWindow } from './api/backup';
export {
  fetchUserUiPreferences,
  saveUserUiPreferences,
  type UserUiPreferences,
} from './api/userPreferences';
export type {
  User,
  UserRole,
  AuthResponse,
  RegisterRequest,
  LoginRequest,
  InvitationDetails,
  PromoteToAdminResponse,
  GetUsersResponse,
  AdminUserRow,
  Group,
  GroupBase,
  GroupMember,
  MyGroupResponse,
  SetMembershipBody,
  MemberRankAction,
} from './api/auth';

export {
  uploadTurtlePhoto,
  quickCheckCarapaceMatch,
  getReviewQueue,
  uploadReviewPacketAdditionalImages,
  getReviewPacket,
  removeReviewPacketAdditionalImage,
  approveReview,
  deleteReviewItem,
  getTurtlesWithFlags,
  clearReleaseFlag,
  getImageUrl,
  getTurtleImageDownloadUrl,
  getTurtleImages,
  getTurtlePrimariesBatch,
  uploadTurtleAdditionalImages,
  uploadTurtleReplaceReference,
  uploadTurtleIdentifierPlastron,
  deleteTurtleAdditionalImage,
  deleteTurtleImage,
  restoreTurtleImage,
  RestoreCollisionError,
  classifyReviewPacket,
  crossCheckReviewPacket,
  searchTurtleImagesByLabel,
  updateTurtleAdditionalImageLabels,
  setTurtleImageLabels,
} from './api/turtle';
export type {
  PhotoType,
  TurtleMatch,
  UploadPhotoResponse,
  QuickCheckMatch,
  QuickCheckResponse,
  LocationHint,
  AdditionalImage,
  ReviewQueueItem,
  FindMetadata,
  ReviewQueueResponse,
  ApproveReviewRequest,
  ApproveReviewResponse,
  UploadFlagOptions,
  UploadExtraFile,
  TurtleImageAdditional,
  TurtleImagesResponse,
  TurtleLooseImage,
  TurtleLooseSource,
  TurtlePrimaryInfo,
  TurtleDeletedImage,
  TurtleDeletedCategory,
  DeleteTurtleImageResponse,
  RestoreTurtleImageResponse,
  TurtleAdditionalLabelSearchMatch,
  GetImageUrlOptions,
} from './api/turtle';

export {
  getTurtleSheetsData,
  createTurtleSheetsData,
  updateTurtleSheetsData,
  markTurtleDeceased,
  getTurtleLookupOptions,
  generatePrimaryId,
  generateTurtleId,
  listSheets,
  listCommunitySheets,
  getLocations,
  getGeneralLocationCatalog,
  addGeneralLocation,
  getAffectedTurtleCount,
  deleteGeneralLocation,
  createSheet,
  getTurtleNames,
  listAllTurtlesFromSheets,
  downloadAdminBackupArchive,
  turtleDataFolderHint,
} from './api/sheets';
export type {
  TurtleSheetsData,
  GetTurtleSheetsDataResponse,
  GetLocationsResponse,
  GeneralLocationCatalog,
  GeneralLocationCatalogResponse,
  AddGeneralLocationRequest,
  AddGeneralLocationResponse,
  ListSheetsResponse,
  GeneratePrimaryIdRequest,
  GeneratePrimaryIdResponse,
  MarkTurtleDeceasedRequest,
  MarkTurtleDeceasedResponse,
  MarkTurtleDeceasedMatch,
  TurtleLookupField,
  GetTurtleLookupOptionsResponse,
  GenerateTurtleIdRequest,
  GenerateTurtleIdResponse,
  CreateTurtleSheetsDataRequest,
  CreateTurtleSheetsDataResponse,
  UpdateTurtleSheetsDataRequest,
  UpdateTurtleSheetsDataResponse,
  CreateSheetRequest,
  CreateSheetResponse,
  TurtleNameEntry,
  ListTurtleNamesResponse,
  ListTurtlesResponse,
} from './api/sheets';
